# Generated by Django 6.0.1 on 2026-01-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtopic',
            name='language',
            field=models.CharField(choices=[('uk', 'Українська'), ('en', 'English')], default='uk', max_length=2),
        ),
        migrations.AlterField(
            model_name='testtext',
            name='language',
            field=models.CharField(choices=[('uk', 'Українська'), ('en', 'English')], default='uk', max_length=2),
        ),
        migrations.AlterField(
            model_name='testtext',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testtopic',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testtopic',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
