# Generated by Django 6.0.1 on 2026-01-21 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='trainer', max_length=30)),
                ('duration_sec', models.IntegerField(default=0)),
                ('typed_chars', models.IntegerField(default=0)),
                ('correct_chars', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('cpm', models.FloatField(default=0.0)),
                ('wpm', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
