# Generated by Django 6.0.1 on 2026-01-27 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uk', 'Українська'), ('en', 'English')], default='uk', max_length=2)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('difficulty', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trainingresult',
            name='correct_chars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainingresult',
            name='duration_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainingresult',
            name='errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainingresult',
            name='mode',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('test', 'Test'), ('game', 'Game')], default='trainer', max_length=10),
        ),
        migrations.AlterField(
            model_name='trainingresult',
            name='typed_chars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainingresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
