# Generated by Django 6.0.1 on 2026-01-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_trainingtext_alter_trainingresult_correct_chars_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingresult',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='trainingtext',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.RemoveField(
            model_name='trainingtext',
            name='difficulty',
        ),
        migrations.AlterField(
            model_name='trainingresult',
            name='duration_sec',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='trainingresult',
            name='mode',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('test', 'Test'), ('lesson', 'Lesson')], default='trainer', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingtext',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
