# Generated by Django 6.0.1 on 2026-01-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lessonprogress_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RenameField(
            model_name='lessonprogress',
            old_name='is_completed',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='last_accuracy',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='last_cpm',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='last_errors',
        ),
        migrations.RemoveField(
            model_name='lessontext',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lessontext',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration_sec',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='lesson',
            name='language',
            field=models.CharField(choices=[('uk', 'Українська'), ('en', 'English')], default='uk', max_length=2),
        ),
        migrations.AddField(
            model_name='lesson',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessontext',
            name='difficulty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lessontext',
            name='language',
            field=models.CharField(choices=[('uk', 'Українська'), ('en', 'English')], default='uk', max_length=2),
        ),
        migrations.AddField(
            model_name='lessontext',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='instruction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='keys_covered',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
